[package]
name = "cosmic-calculator"
version = "0.1.0"
edition = "2021"

[dependencies]
libcosmic = { git = "https://github.com/pop-os/libcosmic", default-features = false, features = ["wayland", "winit"] }

[profile.release]
lto = "thin"
strip = true
